# Generated by Django 4.2.7 on 2023-11-20 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('autor', models.CharField(max_length=50)),
                ('data_cadastro', models.DateTimeField()),
                ('emprestado', models.BooleanField(default=False)),
                ('nome_emprestado', models.CharField(max_length=50)),
                ('data_emprestimo', models.DateTimeField()),
                ('data_devolução', models.DateTimeField()),
                ('tempo_emprestimo', models.DateTimeField()),
            ],
        ),
    ]
